### PR TITLE
runtime: Use `[[Define]]` for the `Symbol.toStringTag` property

### PR DESCRIPTION
**Pull request by ExE-Boss**
See <https://github.com/tc39/proposal-iterator-helpers/issues/115> and **Firefox**’s [Bug 1644581 (comment #6)](https://bugzilla.mozilla.org/show_bug.cgi?id=1644581#c6).

### CODE REVIEW

**Comment by ljharb** [comment]
I filed #400 which uses a conditional; defineProperty won't work in IE < 9, which is an important target for this package.

**Comment by ExE-Boss** [comment]
This will work in **IE &lt; 9**, since it only uses `defineProperty` if the symbol property already exists in `GeneratorPrototype`’s prototype chain.

**Comment by benjamn** [comment]
That's a fair point @ExE-Boss! Do you see value in overriding the existing string, if it's already defined? PR #400 lets the existing string remain unchanged, whereas `defineProperty` would presumably change it. I have no strong opinion here.

**Comment by ExE-Boss** [comment]
Well, PR <https://github.com/facebook/regenerator/pull/400> makes it so that once browsers start shipping `Iterator.prototype[Symbol.toStringTag]`, then `Object.prototype.toString` will return `[object Iterator]` instead of `[object Generator]` for regenerator’s generator objects.

**Comment by ljharb** [comment]
That sounds like the right behavior to me, since that's what the standard will dictate.

**Comment by ExE-Boss** [comment]
But the `%Symbol.toStringTag%` property of `%GeneratorFunction.prototype.prototype%` is `"Generator"`.

**Comment by ljharb** [comment]
I'm a bit confused.

This change was motivated by a web compat concern, where `Gp[Symbol.toStringTag]` was being assigned, but this was breaking it. Are you saying that it's because it should be defining an own property instead of using [[Set]] and hitting a non-writable property up the [[Prototype]] chain?

**Comment by ExE-Boss** [comment]
> Are you saying that it's because it should be defining an own property instead of using [[Set]] and hitting a non-writable property up the [[Prototype]] chain?

Yes.

**Comment by ljharb** [comment]
In that case, i think the helper @benjamn added should be modified to *conditionally* use `Object.defineProperty`, when it's available. It will need to be used in a try/catch, since IE 8 has the method, but it throws on things that aren't HTML elements.

**Comment by ExE-Boss** [comment]
That’s what I’m doing in <https://github.com/facebook/regenerator/pull/402>.

**Pull request closed without merging**
