### PR TITLE
feat: make it strict mode & CSP compatible if possible

### PR DESCRIPTION
**Pull request by Jack-Works**
Use well-known global names if possible

### CODE REVIEW

**Comment by Jack-Works** [comment]
@benjamn hi, can you review this? this is a small PR

**Comment by Jack-Works** [comment]
<table><tbody><tr><td><a href="https://github.com/benjamn"><strong>@benjamn</strong></a> hi, can you review this? this is a small PR</td></tr></tbody></table>

**Comment by benjamn** [comment]
@Jack-Works What do you think about this alternate approach? https://github.com/facebook/regenerator/issues/378#issuecomment-764878050

**Comment by Jack-Works** [comment]
> @Jack-Works What do you think about this alternate approach? [#378 (comment)](https://github.com/facebook/regenerator/issues/378#issuecomment-764878050)

@benjamn hi that's a cool trick but in some environment like [moddable](https://github.com/Moddable-OpenSource/moddable) (a JS engine for embedded env) the `Object.prototype` is frozen. You cannot add things to it. Please at least leave the `globalThis` try.

**Comment by jridgewell** [comment]
I'd recommend using all of `globalThis`, `self`, and `global` before resorting to a monkey patch on `Object.prototype`.

I have a sneaking suspicion that it will cause a massive deoptimization is everything but the newest browsers. The `delete` is going to turn the `Object.prototype` into map-mode, which will slow down every single object access.

**Comment by zloirock** [comment]
I'm proposing it as the most stable and tested way one more time: https://github.com/zloirock/core-js/blob/v3.8.3/packages/core-js/internals/global.js

**Comment by mikecann** [comment]
Has this PR stalled? Would love to see it go in for those of us tring to build things in CSP environments.

**Comment by Jack-Works** [comment]
I'm just waiting for the maintainer to respond. There aren't so many things I need to up-to-date with.

**Comment by edwardxia** [comment]
@Jack-Works This PR will fail Content Security Policy, please check the better way that @zloirocks has linked previously.

**Comment by Jack-Works** [comment]
I have rebased to master to resolve merge conflicts.

**Comment by Jack-Works** [comment]
> @Jack-Works This PR will fail Content Security Policy, please check the better way that @zloirock has linked in previous comment.

Updated

**Comment by juergba** [comment]
Is this issue still relevant? Or is it fixed in _regenerator-runtime_ v.0.13.9?
Thank you

**Comment by zloirock** [comment]
It's fixed only for engines with `globalThis`.

**Comment by poacher2k** [comment]
I keep snoozing this tab "Until next month", hoping every time it re-appears that the PR will have been merged. This really seems like a good fix for the described issue, in addition to being backwards-compatible.

On a side note, I can't remember ever actually have gotten very pissed off when debugging, but when I was debugging the strange CSP issue I had almost a year ago, and finally finding out the reason things were failing, the snarky comment that this PR thankfully removes - certainly had me swearing.

Anyhow, I'm crossing my fingers this will be fixed in January! :)

**Comment by Jack-Works** [comment]
image

I tried as many names as possible. Not only `globalThis` now.

**Comment by Jack-Works** [comment]
closed because nobody from Meta is responding.

**Pull request closed without merging**
