### PR TITLE
fix #299, check that Symbol is not a polyfill

### LINKED ISSUE #299: Broken with polyfill.io
regenerator-runtime: 0.10.5
chrome version 44.0.2403

[This code](https://github.com/facebook/regenerator/blob/ea4de31e4a8151fab67dfa7485b2ac5ede4f8eb3/packages/regenerator-runtime/runtime.js#L417):

```
Gp[toStringTagSymbol] = "Generator";
```

throws:

`Uncaught TypeError: Cannot assign to read only property '__symbol:toStringTag0.123....' of [object Object]`

It doesn't happen in latest chrome.
It's Android users, so we can't ask them to update their browsers...

Do you have any lead that could resolve this ?

Thank you

### PR DESCRIPTION
**Pull request by christophehurpeau**
fix #299

### CODE REVIEW

**Comment by fstoerkle** [comment]
Is there a reason why this PR was closed? We are currently facing the same issue and what love to get that resolved.

**Comment by christophehurpeau** [comment]
for some reason this didn't work, I "fixed" it by doing:

```
<script>window.__SYMBOL_POLYFILL = !window.Symbol || !!window.Symbol.toStringTag</script>
<script src="https://polyfill.io/v2/polyfill.min.js?features=..."></script>
```

And then require regenerator-runtime:

```
if (!global.__SYMBOL_POLYFILL) {
  const globalPolyfillSymbol = Symbol;
  global.Symbol = undefined;
  require('regenerator-runtime/runtime');
  global.Symbol = globalPolyfillSymbol;
} else {
  require('regenerator-runtime/runtime');
}
```

**Comment by fstoerkle** [comment]
Thanks for the update @christophehurpeau. We might work on this later this/next week, let's see if we come up with something

**Comment by christophehurpeau** [comment]
I found out why it didn't work before: I simply had 2 versions of regenerator-runtime in my node_modules.

**Comment by christophehurpeau** [comment]
The build fails beacause `Cannot find module 'regenerator-transform'`, like other recent PR

https://travis-ci.org/facebook/regenerator/pull_requests

**Comment by zloirock** [comment]
It will break compatibility with `core-js`.

**Comment by christophehurpeau** [comment]
fix in polyfill-service : https://github.com/Financial-Times/polyfill-service/pull/1295

**Pull request closed without merging**
